<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\legal_position\Decorator\LegalPosition;

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * {@inheritdoc}
 */
function legal_position_node_presave(EntityInterface $entity) {

  if (LegalPosition::applies($entity)) {
    LegalPosition::create($entity)
      ->preSave();
  }
}

/**
 * Implements hook_node_update().
 *
 * {@inheritdoc}
 */
function legal_position_node_update(EntityInterface $entity) {

  if (LegalPosition::applies($entity)) {
    LegalPosition::create($entity)
      ->postSave();
  }
}

/**
 * Implements hook_node_insert().
 *
 * {@inheritdoc}
 */
function legal_position_node_insert(EntityInterface $entity) {

  if (LegalPosition::applies($entity)) {
    LegalPosition::create($entity)
      ->postSave();
  }
}
