<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\legal_position\Decorator\LegalPosition;

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * {@inheritdoc}
 */
function legal_position_node_presave(EntityInterface $entity) {

  if (LegalPosition::applies($entity)) {
    LegalPosition::create($entity)
      ->preSave();
  }

}

function legal_position_block_view_views_block_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {

  if ($block instanceof \Drupal\views\Plugin\Block\ViewsBlock) {
    $view = $block->getViewExecutable();
    if ($view->id() == 'legal_position_categories') {

    }
  }
  $a = 1;
}
